services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
